import { Check, ChevronDown, ChevronRight, ExternalLink, Filter, GitMerge, HelpCircle, RefreshCw, X } from 'lucide-react';
import { Fragment, useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import ErrorPanel from '../components/ErrorPanel';
import PageHeader from '../components/PageHeader';
import RequestFingerprint from '../components/RequestFingerprint';
import StatusBadge from '../components/StatusBadge';
import { useApiStatus } from '../context/ApiStatusContext';
import { useEvidenceAuth } from '../context/AuthContext';
import { evidenceApi } from '../services/evidenceApi';
import { humanizeKey, truncateMiddle } from '../utils/formatters';

const PAGE_SIZE = 50;

const DEFAULT_SORTING = [{ id: 'source_rows', desc: true }];

const SORT_PARAM_BY_COLUMN = {
  canonical_name: 'entity',
  confidence: 'confidence',
  alias_count: 'aliases',
  mention_count: 'mentions',
  role_count: 'roles',
  confirmed_alias_count: 'confirmed',
  source_rows: 'source_rows',
};

const FILTER_LABELS = {
  canonical_name: 'Entity contains',
  confidence: 'Confidence >=',
  alias_count: 'Aliases >=',
  mention_count: 'Mentions >=',
  role_count: 'Roles >=',
  confirmed_alias_count: 'Confirmed >=',
  source_rows: 'Source rows >=',
};

const ENTITY_COLUMNS = [
  {
    id: 'canonical_name',
    label: 'Entity',
    help: 'Canonical entity generated by ingestion. Filter searches canonical names, aliases, and person ids.',
    filterType: 'text',
    placeholder: 'Name, alias, or id',
    headerClassName: 'min-w-[260px]',
  },
  {
    id: 'confidence',
    label: 'Confidence',
    help: 'Average model/heuristic extraction confidence for this canonical entity. Filter means minimum confidence.',
    filterType: 'number',
    placeholder: '0.75',
    step: '0.01',
    max: '1',
    headerClassName: 'min-w-[120px]',
  },
  {
    id: 'alias_count',
    label: 'Aliases',
    help: 'Number of distinct aliases currently attached to this entity by ingestion. Filter means minimum alias count.',
    filterType: 'number',
    placeholder: '2',
    headerClassName: 'min-w-[100px]',
  },
  {
    id: 'mention_count',
    label: 'Mentions',
    help: 'Number of extracted mentions resolved to this entity. Filter means minimum mention count.',
    filterType: 'number',
    placeholder: '10',
    headerClassName: 'min-w-[110px]',
  },
  {
    id: 'role_count',
    label: 'Roles',
    help: 'Number of role assertions attached to this entity. Filter means minimum role count.',
    filterType: 'number',
    placeholder: '1',
    headerClassName: 'min-w-[90px]',
  },
  {
    id: 'confirmed_alias_count',
    label: 'Confirmed',
    help: 'Number of human alias confirmations recorded for this entity. Filter means minimum confirmation count.',
    filterType: 'number',
    placeholder: '1',
    headerClassName: 'min-w-[120px]',
  },
  {
    id: 'source_rows',
    label: 'Source Rows',
    help: 'Number of source rows merged into this canonical entity. Filter means minimum source-row count.',
    filterType: 'number',
    placeholder: '1',
    headerClassName: 'min-w-[120px]',
  },
];

function confidenceLabel(value) {
  const number = Number(value);
  if (Number.isNaN(number)) {
    return 'n/a';
  }
  return number.toFixed(2);
}

function InfoTip({ label }) {
  return (
    <button
      type="button"
      title={label}
      aria-label={label}
      className="inline-flex rounded-full text-gray-400 hover:text-sky-700 dark:hover:text-sky-300"
    >
      <HelpCircle size={14} aria-hidden="true" />
    </button>
  );
}

function latestAliasDecision(confirmations, alias) {
  const normalized = alias?.normalized_alias;
  if (!normalized) {
    return null;
  }
  return confirmations.find((item) => item.normalized_alias === normalized) || null;
}

function decisionStatus(decision) {
  if (decision === 'confirm') return 'succeeded';
  if (decision === 'reject') return 'failed';
  return 'degraded';
}

function getColumnFilterValue(columnFilters, id) {
  const match = columnFilters.find((filter) => filter.id === id);
  if (match?.value === undefined || match?.value === null) {
    return '';
  }
  return String(match.value).trim();
}

function normalizeColumnFilters(columnFilters) {
  return columnFilters
    .map((filter) => ({ ...filter, value: String(filter.value ?? '').trim() }))
    .filter((filter) => filter.value !== '');
}

function sortingLabel(sorting) {
  const active = sorting[0] || DEFAULT_SORTING[0];
  const label = FILTER_LABELS[active.id]?.replace(' >=', '')?.replace(' contains', '') || humanizeKey(active.id);
  return `${label}: ${active.desc ? 'descending' : 'ascending'}`;
}

function entityColumnValue(entity, columnId) {
  if (columnId === 'canonical_name') {
    return entity.canonical_name || entity.person_id;
  }
  if (columnId === 'confidence') {
    return confidenceLabel(entity.confidence);
  }
  return entity[columnId] || 0;
}

function ColumnHeaderMenu({
  column,
  filterValue,
  isOpen,
  isSorted,
  sortDescending,
  onClearFilter,
  onFilterChange,
  onSetSort,
  onToggle,
}) {
  return (
    <div className="relative">
      <button
        type="button"
        onClick={onToggle}
        className="inline-flex w-full items-center justify-between gap-2 rounded-md px-2 py-1 text-left hover:bg-gray-100 dark:hover:bg-white/10"
        title={`${column.label} filter and sort`}
      >
        <span className="inline-flex min-w-0 items-center gap-1">
          <span className="truncate">{column.label}</span>
          <InfoTip label={column.help} />
        </span>
        <span className="inline-flex items-center gap-1 text-gray-400">
          {filterValue ? <Filter size={13} aria-hidden="true" /> : null}
          {isSorted ? <span className="text-xs text-sky-700 dark:text-sky-300">{sortDescending ? 'down' : 'up'}</span> : null}
          <ChevronDown size={14} aria-hidden="true" />
        </span>
      </button>
      {isOpen ? (
        <div className="absolute left-0 top-full z-40 mt-2 w-72 rounded-lg border border-gray-200 bg-white p-3 text-sm normal-case tracking-normal text-gray-800 shadow-xl dark:border-gray-700 dark:bg-[#101820] dark:text-gray-100">
          <div className="mb-3 text-xs font-semibold uppercase tracking-normal text-gray-500 dark:text-gray-400">Sort</div>
          <div className="mb-4 grid grid-cols-2 gap-2">
            <button
              type="button"
              onClick={() => onSetSort(false)}
              className={`rounded-md border px-2 py-1.5 text-xs font-semibold ${isSorted && !sortDescending ? 'border-sky-600 bg-sky-50 text-sky-800 dark:border-sky-500 dark:bg-sky-950/50 dark:text-sky-200' : 'border-gray-300 hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-white/10'}`}
            >
              Ascending
            </button>
            <button
              type="button"
              onClick={() => onSetSort(true)}
              className={`rounded-md border px-2 py-1.5 text-xs font-semibold ${isSorted && sortDescending ? 'border-sky-600 bg-sky-50 text-sky-800 dark:border-sky-500 dark:bg-sky-950/50 dark:text-sky-200' : 'border-gray-300 hover:bg-gray-50 dark:border-gray-700 dark:hover:bg-white/10'}`}
            >
              Descending
            </button>
          </div>
          <label className="block">
            <span className="mb-1 block text-xs font-semibold uppercase tracking-normal text-gray-500 dark:text-gray-400">
              {column.id === 'canonical_name' ? 'Filter contains' : 'Minimum value'}
            </span>
            <input
              value={filterValue}
              onChange={(event) => onFilterChange(event.target.value)}
              type={column.filterType}
              min={column.filterType === 'number' ? '0' : undefined}
              max={column.max}
              step={column.step || '1'}
              placeholder={column.placeholder}
              className="w-full rounded-md border border-gray-300 bg-white px-2 py-2 text-sm text-gray-950 outline-none focus:border-sky-500 dark:border-gray-700 dark:bg-[#0b1117] dark:text-gray-100"
            />
          </label>
          <div className="mt-3 flex justify-between gap-2">
            <button
              type="button"
              onClick={onClearFilter}
              disabled={!filterValue}
              className="rounded-md border border-gray-300 px-2 py-1.5 text-xs font-semibold text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-40 dark:border-gray-700 dark:text-gray-200 dark:hover:bg-white/10"
            >
              Clear filter
            </button>
            <button
              type="button"
              onClick={onToggle}
              className="rounded-md border border-sky-700 bg-sky-700 px-2 py-1.5 text-xs font-semibold text-white hover:bg-sky-800"
            >
              Done
            </button>
          </div>
        </div>
      ) : null}
    </div>
  );
}

export default function EntitiesPage() {
  const { caseId } = useParams();
  const { getAccessToken } = useEvidenceAuth();
  const { recordFingerprint } = useApiStatus();
  const [columnFilters, setColumnFilters] = useState([]);
  const [sorting, setSorting] = useState(DEFAULT_SORTING);
  const [pagination, setPagination] = useState({ pageIndex: 0, pageSize: PAGE_SIZE });
  const [openColumnMenu, setOpenColumnMenu] = useState(null);
  const [selectedPersonId, setSelectedPersonId] = useState(null);
  const [expanded, setExpanded] = useState({});
  const [rowDetails, setRowDetails] = useState({});
  const [customAlias, setCustomAlias] = useState('');
  const [mergeNote, setMergeNote] = useState('');
  const [reassignTargets, setReassignTargets] = useState({});
  const [state, setState] = useState({
    loading: true,
    detailLoading: false,
    suggestionsLoading: true,
    actionId: null,
    error: null,
    actionError: null,
    entities: [],
    total: 0,
    entity: null,
    suggestions: [],
    decisions: [],
    fingerprint: null,
    detailFingerprint: null,
    actionFingerprint: null,
  });

  const entityLookup = useMemo(() => {
    const map = new Map();
    state.entities.forEach((item) => map.set(item.person_id, item));
    return map;
  }, [state.entities]);

  const normalizedFilters = useMemo(() => normalizeColumnFilters(columnFilters), [columnFilters]);

  const tableQuery = useMemo(() => {
    const activeSort = sorting[0] || DEFAULT_SORTING[0];
    return {
      limit: pagination.pageSize,
      offset: pagination.pageIndex * pagination.pageSize,
      q: getColumnFilterValue(normalizedFilters, 'canonical_name'),
      sort_by: SORT_PARAM_BY_COLUMN[activeSort.id] || 'source_rows',
      sort_dir: activeSort.desc ? 'desc' : 'asc',
      min_confidence: getColumnFilterValue(normalizedFilters, 'confidence'),
      min_aliases: getColumnFilterValue(normalizedFilters, 'alias_count'),
      min_mentions: getColumnFilterValue(normalizedFilters, 'mention_count'),
      min_roles: getColumnFilterValue(normalizedFilters, 'role_count'),
      min_confirmed: getColumnFilterValue(normalizedFilters, 'confirmed_alias_count'),
      min_source_rows: getColumnFilterValue(normalizedFilters, 'source_rows'),
    };
  }, [normalizedFilters, pagination.pageIndex, pagination.pageSize, sorting]);

  const loadEntityDetail = useCallback(async (personId, options = {}) => {
    if (!personId) {
      return null;
    }
    if (!options.silent) {
      setState((current) => ({ ...current, detailLoading: true, actionError: null }));
    }
    try {
      const token = await getAccessToken();
      const result = await evidenceApi.getEntity(caseId, personId, { token });
      recordFingerprint(result, 'Entity detail');
      const entity = result.data?.entity || null;
      setState((current) => ({
        ...current,
        detailLoading: false,
        entity: options.forRow ? current.entity : entity,
        detailFingerprint: options.forRow
          ? current.detailFingerprint
          : {
              id: result.requestFingerprintId,
              correlationId: result.correlationId,
            },
      }));
      if (options.forRow && entity) {
        setRowDetails((current) => ({ ...current, [personId]: entity }));
      }
      return entity;
    } catch (error) {
      setState((current) => ({ ...current, detailLoading: false, actionError: error }));
      return null;
    }
  }, [caseId, getAccessToken, recordFingerprint]);

  const loadEntities = useCallback(async () => {
    setState((current) => ({ ...current, loading: true, error: null }));
    try {
      const token = await getAccessToken();
      const result = await evidenceApi.getEntities(caseId, tableQuery, { token });
      recordFingerprint(result, 'Entities list');
      const entities = result.data?.entities || [];
      setState((current) => ({
        ...current,
        loading: false,
        entities,
        total: result.data?.total || 0,
        fingerprint: {
          id: result.requestFingerprintId,
          correlationId: result.correlationId,
        },
      }));
      if (!selectedPersonId && entities[0]?.person_id) {
        setSelectedPersonId(entities[0].person_id);
      }
    } catch (error) {
      setState((current) => ({ ...current, loading: false, error }));
    }
  }, [caseId, getAccessToken, recordFingerprint, selectedPersonId, tableQuery]);

  const loadSuggestions = useCallback(async () => {
    setState((current) => ({ ...current, suggestionsLoading: true }));
    try {
      const token = await getAccessToken();
      const result = await evidenceApi.getEntityMergeSuggestions(caseId, { limit: 30 }, { token });
      recordFingerprint(result, 'Entity merge suggestions');
      setState((current) => ({
        ...current,
        suggestionsLoading: false,
        suggestions: result.data?.suggestions || [],
        decisions: result.data?.decisions || [],
      }));
    } catch (error) {
      setState((current) => ({ ...current, suggestionsLoading: false, actionError: error }));
    }
  }, [caseId, getAccessToken, recordFingerprint]);

  useEffect(() => {
    const timerId = window.setTimeout(() => {
      loadEntities();
    }, 0);
    return () => window.clearTimeout(timerId);
  }, [loadEntities]);

  useEffect(() => {
    const timerId = window.setTimeout(() => {
      loadSuggestions();
    }, 0);
    return () => window.clearTimeout(timerId);
  }, [loadSuggestions]);

  useEffect(() => {
    const timerId = window.setTimeout(() => {
      loadEntityDetail(selectedPersonId);
    }, 0);
    return () => window.clearTimeout(timerId);
  }, [loadEntityDetail, selectedPersonId]);

  const resetEntityTable = useCallback(() => {
    setColumnFilters([]);
    setSorting(DEFAULT_SORTING);
    setPagination({ pageIndex: 0, pageSize: PAGE_SIZE });
    setSelectedPersonId(null);
    setExpanded({});
    setOpenColumnMenu(null);
  }, []);

  const handleColumnFiltersChange = useCallback((updater) => {
    setColumnFilters((current) => (typeof updater === 'function' ? updater(current) : updater));
    setPagination((current) => ({ ...current, pageIndex: 0 }));
    setSelectedPersonId(null);
    setExpanded({});
  }, []);

  const setColumnFilterValue = useCallback((columnId, value) => {
    handleColumnFiltersChange((current) => {
      const next = current.filter((filter) => filter.id !== columnId);
      if (String(value || '').trim()) {
        next.push({ id: columnId, value });
      }
      return next;
    });
  }, [handleColumnFiltersChange]);

  const clearColumnFilter = useCallback((columnId) => {
    handleColumnFiltersChange((current) => current.filter((filter) => filter.id !== columnId));
  }, [handleColumnFiltersChange]);

  const setColumnSort = useCallback((columnId, desc) => {
    setSorting([{ id: columnId, desc }]);
    setPagination((current) => ({ ...current, pageIndex: 0 }));
  }, []);

  const toggleExpanded = useCallback((personId) => {
    setExpanded((current) => {
      const next = { ...current };
      if (next[personId]) {
        delete next[personId];
        return next;
      }
      next[personId] = true;
      if (!rowDetails[personId]) {
        void loadEntityDetail(personId, { forRow: true, silent: true });
      }
      return next;
    });
  }, [loadEntityDetail, rowDetails]);

  const reviewAlias = useCallback(async (entity, alias, decision) => {
    if (!entity) {
      return;
    }
    const actionId = `${entity.person_id}_${alias.normalized_alias || alias.alias}_${decision}`;
    setState((current) => ({ ...current, actionId, actionError: null }));
    try {
      const token = await getAccessToken();
      const result = await evidenceApi.reviewEntityAlias(
        caseId,
        entity.person_id,
        {
          alias_id: alias.alias_id || null,
          alias: alias.alias,
          normalized_alias: alias.normalized_alias || alias.alias.toLowerCase(),
          decision,
          reviewer_note: decision === 'confirm'
            ? `Confirmed that alias "${alias.alias}" resolves to ${entity.canonical_name}.`
            : `Rejected alias "${alias.alias}" for ${entity.canonical_name}.`,
          confidence: alias.confidence ?? null,
          source_json: {
            source: 'entities_page',
            occurrence_count: alias.occurrence_count,
            source_file_hashes: alias.source_file_hashes || [],
          },
        },
        { token },
      );
      recordFingerprint(result, 'Review entity alias');
      setState((current) => ({
        ...current,
        actionId: null,
        actionFingerprint: {
          id: result.requestFingerprintId,
          correlationId: result.correlationId,
        },
      }));
      await loadEntityDetail(entity.person_id);
      await loadEntityDetail(entity.person_id, { forRow: true, silent: true });
      await loadEntities();
    } catch (error) {
      setState((current) => ({ ...current, actionId: null, actionError: error }));
    }
  }, [caseId, getAccessToken, loadEntities, loadEntityDetail, recordFingerprint]);

  const reassignAlias = useCallback(async (entity, alias) => {
    const targetPersonId = reassignTargets[`${entity.person_id}:${alias.normalized_alias || alias.alias}`];
    if (!entity || !targetPersonId) {
      return;
    }
    const actionId = `${entity.person_id}_${alias.normalized_alias || alias.alias}_reassign`;
    setState((current) => ({ ...current, actionId, actionError: null }));
    try {
      const token = await getAccessToken();
      const result = await evidenceApi.reassignEntityAlias(
        caseId,
        entity.person_id,
        {
          alias_id: alias.alias_id || null,
          alias: alias.alias,
          normalized_alias: alias.normalized_alias || alias.alias.toLowerCase(),
          target_person_id: targetPersonId,
          reviewer_note: `Corrected alias "${alias.alias}" from ${entity.canonical_name} to ${entityLookup.get(targetPersonId)?.canonical_name || targetPersonId}.`,
          confidence: alias.confidence ?? null,
          source_json: {
            source: 'entities_page_reassign',
            occurrence_count: alias.occurrence_count,
          },
        },
        { token },
      );
      recordFingerprint(result, 'Reassign entity alias');
      setState((current) => ({
        ...current,
        actionId: null,
        actionFingerprint: {
          id: result.requestFingerprintId,
          correlationId: result.correlationId,
        },
      }));
      await loadEntityDetail(entity.person_id);
      await loadEntityDetail(entity.person_id, { forRow: true, silent: true });
      await loadEntities();
    } catch (error) {
      setState((current) => ({ ...current, actionId: null, actionError: error }));
    }
  }, [caseId, entityLookup, getAccessToken, loadEntities, loadEntityDetail, reassignTargets, recordFingerprint]);

  const addConfirmedAlias = useCallback(async () => {
    const entity = state.entity;
    const alias = customAlias.trim();
    if (!entity || !alias) {
      return;
    }
    setState((current) => ({ ...current, actionId: 'custom_alias', actionError: null }));
    try {
      const token = await getAccessToken();
      const result = await evidenceApi.reviewEntityAlias(
        caseId,
        entity.person_id,
        {
          alias,
          normalized_alias: alias.toLowerCase().replace(/\s+/g, ' '),
          decision: 'confirm',
          reviewer_note: `Manually confirmed that "${alias}" resolves to ${entity.canonical_name}.`,
          confidence: 1,
          source_json: { source: 'manual_entity_review' },
        },
        { token },
      );
      recordFingerprint(result, 'Add confirmed entity alias');
      setCustomAlias('');
      setState((current) => ({
        ...current,
        actionId: null,
        actionFingerprint: {
          id: result.requestFingerprintId,
          correlationId: result.correlationId,
        },
      }));
      await loadEntityDetail(entity.person_id);
      await loadEntities();
    } catch (error) {
      setState((current) => ({ ...current, actionId: null, actionError: error }));
    }
  }, [caseId, customAlias, getAccessToken, loadEntities, loadEntityDetail, recordFingerprint, state.entity]);

  const decideMergeSuggestion = useCallback(async (suggestion, decision) => {
    const people = suggestion.people || [];
    if (people.length < 2) {
      return;
    }
    const actionId = `${suggestion.suggestion_type}_${suggestion.match_value}_${decision}`;
    setState((current) => ({ ...current, actionId, actionError: null }));
    try {
      const token = await getAccessToken();
      const result = await evidenceApi.createEntityMergeDecision(
        caseId,
        {
          source_person_id: people[0].person_id,
          target_person_id: people[1].person_id,
          decision,
          reviewer_note: mergeNote || `${humanizeKey(decision)} from merge suggestion review.`,
          suggestion_source: suggestion.suggestion_type,
          evidence_json: {
            match_value: suggestion.match_value,
            aliases: suggestion.aliases || [],
            people,
            confidence: suggestion.confidence,
          },
        },
        { token },
      );
      recordFingerprint(result, 'Entity merge decision');
      setMergeNote('');
      setState((current) => ({
        ...current,
        actionId: null,
        actionFingerprint: {
          id: result.requestFingerprintId,
          correlationId: result.correlationId,
        },
      }));
      await loadSuggestions();
    } catch (error) {
      setState((current) => ({ ...current, actionId: null, actionError: error }));
    }
  }, [caseId, getAccessToken, loadSuggestions, mergeNote, recordFingerprint]);

  const entity = state.entity;
  const confirmations = useMemo(() => entity?.alias_confirmations || [], [entity]);
  const confirmedAliases = useMemo(() => confirmations.filter((item) => item.decision === 'confirm'), [confirmations]);
  const activeEntityFilter = getColumnFilterValue(normalizedFilters, 'canonical_name');
  const appliedFilterLabels = normalizedFilters.map((filter) => ({
    id: filter.id,
    label: `${FILTER_LABELS[filter.id] || humanizeKey(filter.id)} ${filter.value}`,
  }));
  const activeSort = sorting[0] || DEFAULT_SORTING[0];
  const currentPage = pagination.pageIndex + 1;
  const totalPages = Math.max(1, Math.ceil((state.total || 0) / pagination.pageSize));
  const canGoPrevious = pagination.pageIndex > 0;
  const canGoNext = pagination.pageIndex + 1 < totalPages;
  const firstVisibleRow = state.total ? pagination.pageIndex * pagination.pageSize + 1 : 0;
  const lastVisibleRow = Math.min(state.total, (pagination.pageIndex + 1) * pagination.pageSize);

  const renderAliasRows = (detailEntity, compact = false) => {
    const detailConfirmations = detailEntity?.alias_confirmations || [];
    return (detailEntity?.aliases || []).slice(0, compact ? 12 : 40).map((alias) => {
      const decision = latestAliasDecision(detailConfirmations, alias);
      const targetKey = `${detailEntity.person_id}:${alias.normalized_alias || alias.alias}`;
      const actionBase = `${detailEntity.person_id}_${alias.normalized_alias || alias.alias}`;
      return (
        <div key={alias.normalized_alias || alias.alias} className="rounded-md border border-gray-200 p-3 text-sm dark:border-gray-800">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div>
              <span className="font-semibold text-gray-950 dark:text-white">{alias.alias}</span>
              <span className="ml-2 text-xs text-gray-500 dark:text-gray-400">
                resolves to {detailEntity.canonical_name}; {alias.occurrence_count || 0} occurrence(s)
              </span>
            </div>
            {decision ? <StatusBadge status={decisionStatus(decision.decision)} label={humanizeKey(decision.decision)} /> : null}
          </div>
          <div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
            <span>{alias.normalized_alias}</span>
            <span>extraction confidence {confidenceLabel(alias.confidence)}</span>
            {decision?.reviewer_display_name || decision?.reviewer_email ? (
              <span>reviewed by {decision.reviewer_display_name || decision.reviewer_email}</span>
            ) : null}
          </div>
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <button
              type="button"
              title={`Confirm alias "${alias.alias}" should resolve to ${detailEntity.canonical_name}.`}
              onClick={() => reviewAlias(detailEntity, alias, 'confirm')}
              disabled={state.actionId === `${actionBase}_confirm`}
              className="inline-flex items-center gap-1 rounded-md border border-emerald-700 bg-emerald-700 px-2 py-1 text-xs font-semibold text-white hover:bg-emerald-800 disabled:opacity-60"
            >
              <Check size={13} aria-hidden="true" />
              Confirm here
            </button>
            <button
              type="button"
              title={`Reject alias "${alias.alias}" for ${detailEntity.canonical_name}.`}
              onClick={() => reviewAlias(detailEntity, alias, 'reject')}
              disabled={state.actionId === `${actionBase}_reject`}
              className="inline-flex items-center gap-1 rounded-md border border-red-300 px-2 py-1 text-xs font-semibold text-red-700 hover:bg-red-50 disabled:opacity-60 dark:border-red-900 dark:text-red-300 dark:hover:bg-red-950/40"
            >
              <X size={13} aria-hidden="true" />
              Reject here
            </button>
            <select
              value={reassignTargets[targetKey] || ''}
              onChange={(event) => setReassignTargets((current) => ({ ...current, [targetKey]: event.target.value }))}
              className="rounded-md border border-gray-300 bg-white px-2 py-1 text-xs text-gray-900 dark:border-gray-700 dark:bg-[#0b1117] dark:text-gray-100"
              title="Choose the correct entity if this alias is attached to the wrong person."
            >
              <option value="">Correct target...</option>
              {state.entities.filter((item) => item.person_id !== detailEntity.person_id).map((item) => (
                <option key={item.person_id} value={item.person_id}>{item.canonical_name}</option>
              ))}
            </select>
            <button
              type="button"
              onClick={() => reassignAlias(detailEntity, alias)}
              disabled={!reassignTargets[targetKey] || state.actionId === `${actionBase}_reassign`}
              className="rounded-md border border-sky-300 px-2 py-1 text-xs font-semibold text-sky-800 hover:bg-sky-50 disabled:cursor-not-allowed disabled:opacity-40 dark:border-sky-800 dark:text-sky-200 dark:hover:bg-sky-950/40"
              title="Reject this alias on the current entity and confirm it on the selected target entity."
            >
              Move alias
            </button>
          </div>
        </div>
      );
    });
  };

  return (
    <div>
      <PageHeader
        title="Entities"
        description={`${state.total} canonical entity records${activeEntityFilter ? ` matching "${activeEntityFilter}"` : ''}. Alias review means deciding which real person an extracted name should resolve to.`}
        actions={
          <button
            type="button"
            onClick={() => {
              loadEntities();
              loadSuggestions();
              if (selectedPersonId) {
                loadEntityDetail(selectedPersonId);
              }
            }}
            className="inline-flex items-center gap-2 rounded-md border border-gray-300 bg-white px-3 py-2 text-sm font-semibold text-gray-800 hover:bg-gray-100 dark:border-gray-700 dark:bg-[#101820] dark:text-gray-100 dark:hover:bg-white/10"
          >
            <RefreshCw size={16} aria-hidden="true" />
            Refresh
          </button>
        }
      />

      {state.error ? <div className="mb-5"><ErrorPanel error={state.error} onRetry={loadEntities} /></div> : null}
      {state.actionError ? <div className="mb-5"><ErrorPanel title="Entity action failed" error={state.actionError} /></div> : null}

      <section className="mb-5 rounded-lg border border-sky-200 bg-sky-50 p-4 text-sm text-sky-950 dark:border-sky-900/60 dark:bg-sky-950/30 dark:text-sky-100">
        <div className="grid gap-3 lg:grid-cols-3">
          <div><strong>Confirm here</strong> records that an alias, such as "grandma", should resolve to the selected entity.</div>
          <div><strong>Reject here</strong> records that the alias should not resolve to the selected entity.</div>
          <div><strong>Move alias</strong> rejects it on the current entity and confirms it on the chosen correct entity.</div>
        </div>
      </section>

      <div className="mb-4 flex flex-col gap-3">
        <div className="rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm text-gray-700 shadow-sm dark:border-gray-800 dark:bg-[#101820] dark:text-gray-300">
          Use each column header menu to sort or filter. Numeric filters are minimum thresholds, and the entity filter searches canonical names, aliases, and person ids.
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <span className="rounded-full border border-gray-300 bg-white px-3 py-1 text-xs font-semibold text-gray-700 dark:border-gray-700 dark:bg-[#101820] dark:text-gray-200">
            {sortingLabel(sorting)}
          </span>
          {appliedFilterLabels.map((filter) => (
            <button
              key={filter.id}
              type="button"
              onClick={() => clearColumnFilter(filter.id)}
              className="inline-flex items-center gap-1 rounded-full border border-sky-200 bg-sky-50 px-3 py-1 text-xs font-semibold text-sky-900 hover:bg-sky-100 dark:border-sky-900/70 dark:bg-sky-950/40 dark:text-sky-100"
              title="Remove this filter"
            >
              {filter.label}
              <X size={12} aria-hidden="true" />
            </button>
          ))}
          {appliedFilterLabels.length ? (
            <button
              type="button"
              onClick={resetEntityTable}
              className="rounded-full border border-gray-300 bg-white px-3 py-1 text-xs font-semibold text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:bg-[#101820] dark:text-gray-200 dark:hover:bg-white/10"
            >
              Clear filters
            </button>
          ) : null}
          {state.fingerprint?.id ? <RequestFingerprint fingerprintId={state.fingerprint.id} correlationId={state.fingerprint.correlationId} label="List fingerprint" /> : null}
          {state.actionFingerprint?.id ? <RequestFingerprint fingerprintId={state.actionFingerprint.id} correlationId={state.actionFingerprint.correlationId} label="Action fingerprint" /> : null}
        </div>
      </div>

      <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_440px]">
        <div>
          <div className="mb-3 rounded-lg border border-gray-200 bg-white p-3 shadow-sm dark:border-gray-800 dark:bg-[#101820] lg:hidden">
            <div className="mb-2 text-xs font-semibold uppercase tracking-normal text-gray-500 dark:text-gray-400">Sort and filter</div>
            <div className="flex flex-wrap gap-2">
              {ENTITY_COLUMNS.map((column) => {
                const filterValue = getColumnFilterValue(columnFilters, column.id);
                const isSorted = activeSort.id === column.id;
                return (
                  <div key={column.id} className="min-w-[150px] flex-1">
                    <ColumnHeaderMenu
                      column={column}
                      filterValue={filterValue}
                      isOpen={openColumnMenu === `mobile_${column.id}`}
                      isSorted={isSorted}
                      sortDescending={activeSort.desc}
                      onClearFilter={() => clearColumnFilter(column.id)}
                      onFilterChange={(value) => setColumnFilterValue(column.id, value)}
                      onSetSort={(desc) => setColumnSort(column.id, desc)}
                      onToggle={() => setOpenColumnMenu((current) => (current === `mobile_${column.id}` ? null : `mobile_${column.id}`))}
                    />
                  </div>
                );
              })}
            </div>
          </div>

          <div className="hidden rounded-lg border border-gray-200 bg-white shadow-sm dark:border-gray-800 dark:bg-[#101820] lg:block">
            <div className="max-h-[calc(100vh-260px)] overflow-auto">
              <table className="min-w-full text-left text-sm">
                <thead className="sticky top-0 z-20 border-b border-gray-200 bg-gray-50 text-xs font-semibold uppercase tracking-normal text-gray-500 dark:border-gray-800 dark:bg-[#0c1218] dark:text-gray-400">
                  <tr>
                    <th className="w-10 px-2 py-2" />
                    {ENTITY_COLUMNS.map((column) => {
                      const filterValue = getColumnFilterValue(columnFilters, column.id);
                      const isSorted = activeSort.id === column.id;
                      return (
                        <th key={column.id} className={`px-2 py-2 align-top ${column.headerClassName || ''}`}>
                          <ColumnHeaderMenu
                            column={column}
                            filterValue={filterValue}
                            isOpen={openColumnMenu === column.id}
                            isSorted={isSorted}
                            sortDescending={activeSort.desc}
                            onClearFilter={() => clearColumnFilter(column.id)}
                            onFilterChange={(value) => setColumnFilterValue(column.id, value)}
                            onSetSort={(desc) => setColumnSort(column.id, desc)}
                            onToggle={() => setOpenColumnMenu((current) => (current === column.id ? null : column.id))}
                          />
                        </th>
                      );
                    })}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100 dark:divide-gray-800">
                  {state.entities.map((item) => {
                    const isExpanded = Boolean(expanded[item.person_id]);
                    const detail = rowDetails[item.person_id];
                    return (
                      <Fragment key={item.person_id}>
                        <tr className="hover:bg-gray-50 dark:hover:bg-white/[0.03]">
                          <td className="px-2 py-2 align-top">
                            <button
                              type="button"
                              onClick={() => toggleExpanded(item.person_id)}
                              className="rounded-md p-1 hover:bg-gray-100 dark:hover:bg-white/10"
                              title="Expand aliases"
                            >
                              {isExpanded ? <ChevronDown size={16} aria-hidden="true" /> : <ChevronRight size={16} aria-hidden="true" />}
                            </button>
                          </td>
                          <td className="px-3 py-2 align-top">
                            <div className="flex items-start gap-2">
                              <button
                                type="button"
                                onClick={() => setSelectedPersonId(item.person_id)}
                                className={`text-left font-semibold ${selectedPersonId === item.person_id ? 'text-sky-700 dark:text-sky-300' : 'text-gray-950 hover:text-sky-700 dark:text-white dark:hover:text-sky-300'}`}
                              >
                                {item.canonical_name || item.person_id}
                                <span className="block text-xs font-normal text-gray-500 dark:text-gray-400">{truncateMiddle(item.person_id, 28)}</span>
                              </button>
                              <Link to={`/evidence/cases/${caseId}/entities/${item.person_id}`} className="mt-0.5 text-gray-400 hover:text-sky-700 dark:hover:text-sky-300" title="Open entity page">
                                <ExternalLink size={14} aria-hidden="true" />
                              </Link>
                            </div>
                          </td>
                          {ENTITY_COLUMNS.slice(1).map((column) => (
                            <td key={column.id} className="px-3 py-2 align-top text-gray-700 dark:text-gray-300">
                              {entityColumnValue(item, column.id)}
                            </td>
                          ))}
                        </tr>
                        {isExpanded ? (
                          <tr>
                            <td colSpan={ENTITY_COLUMNS.length + 1} className="bg-gray-50 px-4 py-3 dark:bg-black/20">
                              {detail ? (
                                <div>
                                  <div className="mb-2 text-xs font-semibold uppercase tracking-normal text-gray-500 dark:text-gray-400">
                                    Aliases currently attached to {detail.canonical_name}
                                  </div>
                                  <div className="grid gap-2 xl:grid-cols-2">{renderAliasRows(detail, true)}</div>
                                </div>
                              ) : (
                                <div className="text-sm text-gray-600 dark:text-gray-400">Loading aliases...</div>
                              )}
                            </td>
                          </tr>
                        ) : null}
                      </Fragment>
                    );
                  })}
                  {!state.entities.length ? (
                    <tr>
                      <td colSpan={ENTITY_COLUMNS.length + 1} className="px-4 py-8 text-center text-sm text-gray-500 dark:text-gray-400">
                        {state.loading ? 'Loading entities' : 'No entities matched'}
                      </td>
                    </tr>
                  ) : null}
                </tbody>
              </table>
            </div>
          </div>

          <div className="space-y-3 lg:hidden">
            {state.entities.map((item) => {
              const isExpanded = Boolean(expanded[item.person_id]);
              const detail = rowDetails[item.person_id];
              return (
                <section key={item.person_id} className="rounded-lg border border-gray-200 bg-white p-3 shadow-sm dark:border-gray-800 dark:bg-[#101820]">
                  <div className="flex items-start justify-between gap-3">
                    <button
                      type="button"
                      onClick={() => setSelectedPersonId(item.person_id)}
                      className={`min-w-0 text-left font-semibold ${selectedPersonId === item.person_id ? 'text-sky-700 dark:text-sky-300' : 'text-gray-950 dark:text-white'}`}
                    >
                      {item.canonical_name || item.person_id}
                      <span className="block text-xs font-normal text-gray-500 dark:text-gray-400">{truncateMiddle(item.person_id, 32)}</span>
                    </button>
                    <Link to={`/evidence/cases/${caseId}/entities/${item.person_id}`} className="text-gray-400 hover:text-sky-700 dark:hover:text-sky-300" title="Open entity page">
                      <ExternalLink size={15} aria-hidden="true" />
                    </Link>
                  </div>
                  <div className="mt-3 grid grid-cols-2 gap-2 text-sm sm:grid-cols-3">
                    {ENTITY_COLUMNS.slice(1).map((column) => (
                      <div key={column.id} className="rounded-md bg-gray-50 p-2 dark:bg-black/20">
                        <div className="text-xs font-semibold uppercase tracking-normal text-gray-500 dark:text-gray-400">{column.label}</div>
                        <div className="text-gray-950 dark:text-white">{entityColumnValue(item, column.id)}</div>
                      </div>
                    ))}
                  </div>
                  <button
                    type="button"
                    onClick={() => toggleExpanded(item.person_id)}
                    className="mt-3 inline-flex items-center gap-1 rounded-md border border-gray-300 px-2 py-1 text-xs font-semibold text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-200 dark:hover:bg-white/10"
                  >
                    {isExpanded ? <ChevronDown size={14} aria-hidden="true" /> : <ChevronRight size={14} aria-hidden="true" />}
                    Aliases
                  </button>
                  {isExpanded ? (
                    <div className="mt-3">
                      {detail ? (
                        <div className="space-y-2">{renderAliasRows(detail, true)}</div>
                      ) : (
                        <div className="text-sm text-gray-600 dark:text-gray-400">Loading aliases...</div>
                      )}
                    </div>
                  ) : null}
                </section>
              );
            })}
            {!state.entities.length ? (
              <div className="rounded-lg border border-gray-200 bg-white px-4 py-8 text-center text-sm text-gray-500 shadow-sm dark:border-gray-800 dark:bg-[#101820] dark:text-gray-400">
                {state.loading ? 'Loading entities' : 'No entities matched'}
              </div>
            ) : null}
          </div>

          <div className="mt-3 flex flex-col gap-3 rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm text-gray-700 shadow-sm dark:border-gray-800 dark:bg-[#101820] dark:text-gray-300 sm:flex-row sm:items-center sm:justify-between">
            <span>
              Showing {firstVisibleRow}-{lastVisibleRow} of {state.total} entities; page {currentPage} of {totalPages}
            </span>
            <div className="flex flex-wrap items-center gap-2">
              <select
                value={pagination.pageSize}
                onChange={(event) => setPagination({ pageIndex: 0, pageSize: Number(event.target.value) })}
                className="rounded-md border border-gray-300 bg-white px-2 py-1.5 text-sm text-gray-900 dark:border-gray-700 dark:bg-[#0b1117] dark:text-gray-100"
              >
                {[25, 50, 100].map((size) => <option key={size} value={size}>{size} rows</option>)}
              </select>
              <button
                type="button"
                onClick={() => setPagination((current) => ({ ...current, pageIndex: Math.max(0, current.pageIndex - 1) }))}
                disabled={!canGoPrevious || state.loading}
                className="rounded-md border border-gray-300 bg-white px-3 py-1.5 font-semibold text-gray-800 hover:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-700 dark:bg-[#101820] dark:text-gray-100 dark:hover:bg-white/10"
              >
                Previous
              </button>
              <button
                type="button"
                onClick={() => setPagination((current) => ({ ...current, pageIndex: current.pageIndex + 1 }))}
                disabled={!canGoNext || state.loading}
                className="rounded-md border border-gray-300 bg-white px-3 py-1.5 font-semibold text-gray-800 hover:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-50 dark:border-gray-700 dark:bg-[#101820] dark:text-gray-100 dark:hover:bg-white/10"
              >
                Next
              </button>
            </div>
          </div>

          <section className="mt-4 rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-[#101820]">
            <div className="mb-3 flex items-center justify-between gap-3">
              <h3 className="text-base font-semibold text-gray-950 dark:text-white">Merge Suggestions</h3>
              <StatusBadge status={state.suggestionsLoading ? 'running' : 'configured'} label={`${state.suggestions.length} suggestion(s)`} />
            </div>
            <label className="mb-3 block">
              <span className="text-xs font-semibold uppercase tracking-normal text-gray-500 dark:text-gray-400">Decision note</span>
              <input value={mergeNote} onChange={(event) => setMergeNote(event.target.value)} placeholder="Optional note for merge/reject decisions" className="mt-2 w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-950 dark:border-gray-700 dark:bg-[#0b1117] dark:text-gray-100" />
            </label>
            <div className="space-y-3">
              {state.suggestions.slice(0, 8).map((suggestion) => {
                const people = suggestion.people || [];
                const actionBase = `${suggestion.suggestion_type}_${suggestion.match_value}`;
                return (
                  <div key={actionBase} className="rounded-md border border-gray-200 p-3 text-sm dark:border-gray-800">
                    <div className="flex flex-wrap items-center gap-2">
                      <StatusBadge status="degraded" label={humanizeKey(suggestion.suggestion_type)} />
                      <span className="font-semibold text-gray-900 dark:text-gray-100">{suggestion.match_value}</span>
                      <span className="text-gray-500 dark:text-gray-400">confidence {confidenceLabel(suggestion.confidence)}</span>
                    </div>
                    <ul className="mt-2 space-y-1 text-gray-700 dark:text-gray-300">
                      {people.map((person) => (
                        <li key={person.person_id}>{person.canonical_name} <span className="text-xs text-gray-500">({truncateMiddle(person.person_id, 18)})</span></li>
                      ))}
                    </ul>
                    {people.length >= 2 ? (
                      <div className="mt-3 flex flex-wrap gap-2">
                        <button type="button" onClick={() => decideMergeSuggestion(suggestion, 'merge')} disabled={state.actionId === `${actionBase}_merge`} className="inline-flex items-center gap-1 rounded-md border border-emerald-700 bg-emerald-700 px-2 py-1 text-xs font-semibold text-white hover:bg-emerald-800 disabled:opacity-60">
                          <GitMerge size={13} aria-hidden="true" />
                          Merge first pair
                        </button>
                        <button type="button" onClick={() => decideMergeSuggestion(suggestion, 'reject')} disabled={state.actionId === `${actionBase}_reject`} className="inline-flex items-center gap-1 rounded-md border border-red-300 px-2 py-1 text-xs font-semibold text-red-700 hover:bg-red-50 disabled:opacity-60 dark:border-red-900 dark:text-red-300 dark:hover:bg-red-950/40">
                          <X size={13} aria-hidden="true" />
                          Reject pair
                        </button>
                      </div>
                    ) : null}
                  </div>
                );
              })}
              {!state.suggestions.length ? <p className="text-sm text-gray-600 dark:text-gray-400">No duplicate suggestions returned.</p> : null}
            </div>
          </section>
        </div>

        <aside className="space-y-5">
          <section className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-[#101820]">
            <div className="flex items-start justify-between gap-3">
              <div>
                <h3 className="text-base font-semibold text-gray-950 dark:text-white">{entity?.canonical_name || 'Select an entity'}</h3>
                <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">{entity ? truncateMiddle(entity.person_id, 36) : 'Choose a row to inspect aliases and provenance.'}</p>
              </div>
              {entity ? <StatusBadge status="configured" label={entity.entity_type || 'entity'} /> : null}
            </div>
            {state.detailFingerprint?.id ? <div className="mt-3"><RequestFingerprint fingerprintId={state.detailFingerprint.id} correlationId={state.detailFingerprint.correlationId} compact /></div> : null}
            {entity ? (
              <div className="mt-4 grid grid-cols-3 gap-2 text-sm">
                <div>
                  <div className="flex items-center gap-1 text-xs font-semibold uppercase tracking-normal text-gray-500 dark:text-gray-400">Confidence <InfoTip label="Average extraction/entity-resolution confidence from ingestion." /></div>
                  <div className="text-gray-950 dark:text-white">{confidenceLabel(entity.confidence)}</div>
                </div>
                <div>
                  <div className="text-xs font-semibold uppercase tracking-normal text-gray-500 dark:text-gray-400">Source Rows</div>
                  <div className="text-gray-950 dark:text-white">{entity.source_rows || 0}</div>
                </div>
                <div>
                  <div className="flex items-center gap-1 text-xs font-semibold uppercase tracking-normal text-gray-500 dark:text-gray-400">Confirmed <InfoTip label="Human alias confirmations for this entity. The confirmation record includes who confirmed it." /></div>
                  <div className="text-gray-950 dark:text-white">{confirmedAliases.length}</div>
                </div>
              </div>
            ) : null}
            {entity ? (
              <Link to={`/evidence/cases/${caseId}/entities/${entity.person_id}`} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-sky-700 hover:text-sky-900 dark:text-sky-300 dark:hover:text-sky-100">
                <ExternalLink size={15} aria-hidden="true" />
                Open full entity page
              </Link>
            ) : null}
          </section>

          {entity ? (
            <>
              <section className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-[#101820]">
                <h3 className="flex items-center gap-1 text-base font-semibold text-gray-950 dark:text-white">
                  Add Confirmed Alias
                  <InfoTip label="Use this only when you know another name, typo, nickname, role, or spelling should resolve to this selected entity." />
                </h3>
                <div className="mt-3 flex gap-2">
                  <input value={customAlias} onChange={(event) => setCustomAlias(event.target.value)} placeholder="Example: Kayla Willson" className="min-w-0 flex-1 rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-950 dark:border-gray-700 dark:bg-[#0b1117] dark:text-gray-100" />
                  <button type="button" onClick={addConfirmedAlias} disabled={!customAlias.trim() || state.actionId === 'custom_alias'} className="inline-flex items-center gap-1 rounded-md border border-emerald-700 bg-emerald-700 px-3 py-2 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-60">
                    <Check size={15} aria-hidden="true" />
                    Add
                  </button>
                </div>
              </section>

              <section className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-[#101820]">
                <h3 className="text-base font-semibold text-gray-950 dark:text-white">Aliases For {entity.canonical_name}</h3>
                <div className="mt-3 space-y-2">{renderAliasRows(entity)}</div>
              </section>

              <section className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-800 dark:bg-[#101820]">
                <h3 className="text-base font-semibold text-gray-950 dark:text-white">Documents Mentioning This Entity</h3>
                <ul className="mt-3 max-h-56 space-y-2 overflow-auto text-sm text-gray-700 dark:text-gray-300">
                  {(entity.document_mentions || []).slice(0, 20).map((document) => (
                    <li key={document.file_hash} className="rounded-md bg-gray-50 p-2 dark:bg-black/20">
                      {document.file_id ? (
                        <Link to={`/evidence/cases/${caseId}/documents/${document.file_id}`} className="font-semibold text-sky-700 hover:text-sky-900 dark:text-sky-300">
                          {document.original_filename || document.file_hash}
                        </Link>
                      ) : (
                        <span className="font-semibold">{document.original_filename || document.file_hash}</span>
                      )}
                      <span className="block text-xs text-gray-500 dark:text-gray-400">
                        {document.mention_count} mention(s); pages {(document.pages || []).slice(0, 8).join(', ') || 'n/a'}
                      </span>
                    </li>
                  ))}
                </ul>
              </section>
            </>
          ) : null}
        </aside>
      </div>
    </div>
  );
}
